In [5]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [6]:
data = pd.read_csv('winequality_red.csv')

In [7]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [27]:
x = data.drop(columns='quality')

In [28]:
y= data.quality

In [29]:
x_train , x_test, y_train,y_test = train_test_split(x,y,random_state = 20)

In [60]:
knn1 = KNeighborsClassifier()

In [61]:
knn1.fit(x_train,y_train)

KNeighborsClassifier()

In [62]:
pickle.dump(knn1,open('knn1.pkl' , 'wb'))

In [32]:
knn.score(x_test, y_test)

0.5175

In [49]:
pram  = {
    'n_neighbors':[3,5,7,9,12,13,15,17,21],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : [10 , 15 , 20 , 25 , 30 , 35 , 45 , 50 ],
    'p' : [1,2],
    'weights' : ['uniform', 'distance']
    
    
    
}

In [50]:
grid_cv = GridSearchCV(knn,param_grid=pram )

In [51]:
grid_cv.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(n_neighbors=17, p=1),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 45, 50],
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [52]:
grid_cv.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 21,
 'p': 1,
 'weights': 'distance'}

In [53]:
knn = KNeighborsClassifier(n_neighbors=21,p= 1 ,weights='distance' , leaf_size=10 , algorithm='auto')

In [54]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [55]:
knn.score(x_test,y_test)

0.6325

In [57]:
import pickle
pickle.dump(knn, open("knn.pkl" , "wb"))

In [58]:
pwd

'C:\\Users\\win10\\jupyter\\ML masters\\Decision tree (1)\\Decision tree'

In [63]:
ls

 Volume in drive C has no label.
 Volume Serial Number is FA55-E833

 Directory of C:\Users\win10\jupyter\ML masters\Decision tree (1)\Decision tree

10/10/2021  04:03 PM    <DIR>          .
10/10/2021  04:03 PM    <DIR>          ..
10/10/2021  03:25 PM    <DIR>          .ipynb_checkpoints
01/02/2020  11:00 PM             1,750 app.py
01/03/2020  02:48 PM               157 class_distribution.csv
01/06/2020  02:44 PM            49,991 cv1.png
01/06/2020  02:45 PM             2,548 cv2.png
01/06/2020  02:45 PM             5,246 cv3.png
01/06/2020  02:45 PM             4,474 cv4.png
01/03/2020  04:33 PM             6,245 data_class.PNG
10/10/2021  03:28 PM        12,777,420 Decision tree practical with random forest .ipynb
10/03/2021  12:30 PM         8,222,985 Decision_tree.ipynb
01/02/2020  02:57 PM            14,298 Decision_tree1.png
01/02/2020  10:56 PM             5,645 Decision_tree-deploy.png
01/17/2020  03:49 PM    <DIR>          DecisionTree_DEPLOYMENT
10/03/2021  02:42 PM      

In [71]:
knn.predict([x_test.iloc[0]])

array([6], dtype=int64)

In [69]:
x_test.iloc[0]

fixed acidity            7.10000
volatile acidity         0.27000
citric acid              0.60000
residual sugar           2.10000
chlorides                0.07400
free sulfur dioxide     17.00000
total sulfur dioxide    25.00000
density                  0.99814
pH                       3.38000
sulphates                0.72000
alcohol                 10.60000
Name: 1508, dtype: float64

In [72]:
data 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [73]:
from sklearn.svm import SVC

In [74]:
svc= SVC()
svc.fit(x_train,y_train)

SVC()

In [75]:
svc.score(x_test,y_test)

0.5

In [88]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ],
        'C':[.1,.4 , .6 , 1,2,3,100,200,500],
        'gamma':[.001,.1,.4,.004,.003]
    } 
svm_grid = GridSearchCV(svc , param_grid=param , verbose=3 )
svm_grid.fit(x_train,y_train)

Fitting 5 folds for each of 180 candidates, totalling 900 fits
[CV] C=0.1, gamma=0.001, kernel=linear ...............................
[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.600, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.525, total=   0.3s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................
[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.575, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.4s remaining:    0.0s


[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.600, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................
[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.548, total=   0.3s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.517, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.500, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.479, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.483, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.510, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] .

KeyboardInterrupt: 

In [ ]:
svm_grid.best_params_

In [85]:
svc1 = SVC(kernel='poly')
svc1.fit(x_train,y_train)

SVC(kernel='poly')

In [86]:
svc1.score(x_test,y_test)

0.49

In [87]:
x_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
400             6.6             0.735         0.02            7.90      0.122   
35              7.8             0.645         0.00            5.50      0.086   
641             9.5             0.590         0.44            2.30      0.071   
721             8.9             0.480         0.24            2.85      0.094   
1501            7.8             0.820         0.29            4.30      0.083   
...             ...               ...          ...             ...        ...   
924             8.6             0.470         0.27            2.30      0.055   
1247            7.4             0.550         0.19            1.80      0.082   
271            11.5             0.180         0.51            4.00      0.104   
474            10.5             0.280         0.51            1.70      0.080   
1379            7.5             0.570         0.02            2.60      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
400                  68.0                 124.0  0.99940  3.47       0.53   
35                    5.0                  18.0  0.99860  3.40       0.55   
641                  21.0                  68.0  0.99920  3.46       0.63   
721                  35.0                 106.0  0.99820  3.10       0.53   
1501                 21.0                  64.0  0.99642  3.16       0.53   
...                   ...                   ...      ...   ...        ...   
924                  14.0                  28.0  0.99516  3.18       0.80   
1247                 15.0                  34.0  0.99655  3.49       0.68   
271                   4.0                  23.0  0.99960  3.28       0.97   
474                  10.0                  24.0  0.99820  3.20       0.89   
1379                 11.0                  35.0  0.99557  3.36       0.62   

      alcohol  
400       9.9  
35        9.6  
641       9.5  
721       9.2  
1501      9.4  
...       ...  
924      11.2  
1247     10.5  
271      10.1  
474       9.4  
1379     10.8  

[1199 rows x 11 columns]

In [90]:
df = pd.read_csv('Admission_Prediction.csv')

In [91]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [112]:
x = df.drop(['Serial No.', 'Chance of Admit'] , axis=1)
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [113]:
y = df['Chance of Admit']

In [114]:
x_train , x_test , y_train,y_test = train_test_split(x,y,random_state = 30 , test_size = .20)

In [115]:
from sklearn.svm import SVR

In [116]:
svr = SVR()

In [117]:
svr.fit(x_train, y_train)

SVR()

In [118]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [105]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [108]:
df['TOEFL Score'] =df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [109]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [110]:
df

Serial No.   GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1  337.000000        118.0                4.0  4.5  4.5  9.65   
1             2  324.000000        107.0                4.0  4.0  4.5  8.87   
2             3  316.558763        104.0                3.0  3.0  3.5  8.00   
3             4  322.000000        110.0                3.0  3.5  2.5  8.67   
4             5  314.000000        103.0                2.0  2.0  3.0  8.21   
..          ...         ...          ...                ...  ...  ...   ...   
495         496  332.000000        108.0                5.0  4.5  4.0  9.02   
496         497  337.000000        117.0                5.0  5.0  5.0  9.87   
497         498  330.000000        120.0                5.0  4.5  5.0  9.56   
498         499  312.000000        103.0                4.0  4.0  5.0  8.43   
499         500  327.000000        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [119]:
from sklearn.metrics import r2_score
r2_score(y_test ,  svr.predict(x_test))

0.6774861142346673

In [120]:
svr.predict(x_test)

array([0.79688575, 0.56869993, 0.70213979, 0.63957666, 0.83300249,
       0.75707761, 0.65994706, 0.68822501, 0.73425829, 0.74644011,
       0.83586246, 0.68361861, 0.7742846 , 0.89252382, 0.81404201,
       0.82819776, 0.55198519, 0.60052276, 0.75981017, 0.71735058,
       0.70996637, 0.70163294, 0.79465708, 0.81204083, 0.77420576,
       0.56782111, 0.63432782, 0.68000782, 0.62334513, 0.58584246,
       0.6721899 , 0.54055777, 0.79251405, 0.64200758, 0.6673232 ,
       0.66244129, 0.6528857 , 0.79952426, 0.55052807, 0.662     ,
       0.57613553, 0.70849189, 0.68005545, 0.66963298, 0.78661726,
       0.6573585 , 0.92081692, 0.63184235, 0.62744472, 0.78123402,
       0.89119762, 0.69692383, 0.79749674, 0.69565313, 0.67689525,
       0.88664598, 0.63801105, 0.53762574, 0.62869004, 0.71534898,
       0.78286732, 0.68986065, 0.73407167, 0.64214697, 0.71423013,
       0.66859242, 0.66567013, 0.62528752, 0.86875038, 0.68531222,
       0.526498  , 0.87626977, 0.6520002 , 0.5400567 , 0.65004

In [123]:
svr.predict([x.iloc[0]])

array([0.89252382])

In [124]:
y[0]

0.92

In [125]:
svr.score(x_test,y_test)

0.6774861142346673

In [ ]:
svc.score()

# stacking 

In [127]:
import pandas as pd 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [128]:
data = pd.read_csv('winequality_red.csv')

In [129]:
data 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [142]:
x = data.drop(columns='quality')
y = data.quality

In [143]:
train , val_train , test , val_test  = train_test_split(x,y,test_size = .50 , random_state = 30)

In [144]:
x_train , x_test , y_train, y_test = train_test_split(train ,test,random_state = 30 , test_size = .20)

In [145]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [146]:
knn.score(x_test,y_test)

0.54375

In [147]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [148]:
svc.score(x_test,y_test)

0.4875

In [149]:
predcition_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [150]:
predcition_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 5, 4,
       6, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 4, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 7, 6, 5, 5, 5, 6,
       5, 5, 5, 7, 6, 7, 6, 7, 5, 6, 5, 5, 5, 6, 5, 7, 6, 5, 6, 5, 7, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 5, 5, 5, 5,
       6, 5, 6, 5, 4, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 4, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6,
       6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6,
       7, 5, 6, 7, 5, 4, 6, 7, 5, 5, 6, 5, 5, 6, 5,

In [151]:
prediction_svc

array([6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [153]:
input3 = np.column_stack((predcition_knn,prediction_svc))

In [155]:
output = val_test

In [156]:
output


1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [158]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  5  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [159]:
rf = RandomForestClassifier()

In [160]:
rf.fit(input3,output)

RandomForestClassifier()

In [161]:
rf.score(x_test,y_test)

ValueError: Number of features of the model must match the input. Model n_features is 2 and input n_features is 11 

In [ ]:
knn
svc
rf

In [162]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [164]:
output_stack1 = np.column_stack ((knn_output,svc_output))

In [165]:
rf.predict(output_stack1)

array([5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 5, 5], dtype=int64)

In [166]:
rf.score(output_stack1 , y_test)

0.55

In [ ]:
https://archive.ics.uci.edu/ml/datasets/Activity+recognition+with+healthy+older+people+using+a+batteryless+wearable+sensor